all:
  hosts:
    okd-single-node:
      ansible_host: "{{ lookup('file', 'terraform/instance_ip.txt') }}"
      ansible_user: "okd-user"
      ansible_ssh_private_key_file: "terraform/ssh-keypair/okd-user-rsa"
